// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApiWithDatabase.Models;

namespace WebApiWithDatabase.Migrations
{
    [DbContext(typeof(DbContextClass))]
    [Migration("20210914073401_FirstMigration")]
    partial class FirstMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.18")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WebApiWithDatabase.Models.CountryClass", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Officialrepresentative")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("areaInSqKm")
                        .HasColumnType("float");

                    b.Property<string>("countryname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("populationInCr")
                        .HasColumnType("float");

                    b.HasKey("id");

                    b.ToTable("countries");
                });
#pragma warning restore 612, 618
        }
    }
}
